### ISSUE TITLE
Session Authenticator refresh test fails intermittently

### ISSUE THREAD

**Issue by vmatyusGitHub** [IBM/cloudant-go-sdk#99] opened 2021-02-10 08:20 UTC
**Describe the bug**
Approximatly 1 out of 10 runs the test `Test authentication refresh` is failing. I encounter this problem during pipeline execution equally on Jenkins and Travis.

Here are the logs that I collected:
<details>
  <summary>Jenkins log</summary>
  <p>
  
  ```bash
  [2021-02-09T17:15:30.748Z] /home/jenkins/workspace/loudant-go-sdk_88-remove-core-v4/auth/couchdb_session_authenticator_test.go:37
[2021-02-09T17:15:30.748Z]   with standard test server
[2021-02-09T17:15:30.748Z]   /home/jenkins/workspace/loudant-go-sdk_88-remove-core-v4/auth/couchdb_session_authenticator_test.go:108
[2021-02-09T17:15:30.748Z]     Test authentication refresh [It]
[2021-02-09T17:15:30.748Z]     /home/jenkins/workspace/loudant-go-sdk_88-remove-core-v4/auth/couchdb_session_authenticator_test.go:215
[2021-02-09T17:15:30.748Z]
[2021-02-09T17:15:30.748Z]     Expected
[2021-02-09T17:15:30.748Z]         <*http.Cookie | 0xc00034a000>: {
[2021-02-09T17:15:30.748Z]             Name: "AuthSession",
[2021-02-09T17:15:30.748Z]             Value: "fakefake-2",
[2021-02-09T17:15:30.748Z]             Path: "",
[2021-02-09T17:15:30.748Z]             Domain: "",
[2021-02-09T17:15:30.748Z]             Expires: 2021-02-10T17:13:28Z,
[2021-02-09T17:15:30.748Z]             RawExpires: "Wed, 10 Feb 2021 17:13:28 GMT",
[2021-02-09T17:15:30.748Z]             MaxAge: 0,
[2021-02-09T17:15:30.748Z]             Secure: false,
[2021-02-09T17:15:30.748Z]             HttpOnly: false,
[2021-02-09T17:15:30.748Z]             SameSite: 0,
[2021-02-09T17:15:30.748Z]             Raw: "AuthSession=fakefake-2; Expires=Wed, 10 Feb 2021 17:13:28 GMT",
[2021-02-09T17:15:30.748Z]             Unparsed: nil,
[2021-02-09T17:15:30.748Z]         }
[2021-02-09T17:15:30.748Z]     to equal
[2021-02-09T17:15:30.748Z]         <*http.Cookie | 0xc000416160>: {
[2021-02-09T17:15:30.748Z]             Name: "AuthSession",
[2021-02-09T17:15:30.748Z]             Value: "fakefake-1",
[2021-02-09T17:15:30.748Z]             Path: "",
[2021-02-09T17:15:30.748Z]             Domain: "",
[2021-02-09T17:15:30.748Z]             Expires: 2021-02-10T17:14:28Z,
[2021-02-09T17:15:30.748Z]             RawExpires: "Wed, 10 Feb 2021 17:14:28 GMT",
[2021-02-09T17:15:30.748Z]             MaxAge: 0,
[2021-02-09T17:15:30.748Z]             Secure: false,
[2021-02-09T17:15:30.748Z]             HttpOnly: false,
[2021-02-09T17:15:30.748Z]             SameSite: 0,
[2021-02-09T17:15:30.748Z]             Raw: "AuthSession=fakefake-1; Expires=Wed, 10 Feb 2021 17:14:28 GMT",
[2021-02-09T17:15:30.748Z]             Unparsed: nil,
[2021-02-09T17:15:30.748Z]         }
[2021-02-09T17:15:30.748Z]
[2021-02-09T17:15:30.748Z]     /home/jenkins/workspace/loudant-go-sdk_88-remove-core-v4/auth/couchdb_session_authenticator_test.go:240
```
</p>
</details>

<details>
  <summary>Travis log</summary>
  <p>
  
  ```bash
  • Failure [1.006 seconds]
305Authenticator Unit Tests
306/home/travis/gopath/src/github.com/IBM/cloudant-go-sdk/auth/couchdb_session_authenticator_test.go:37
307  with standard test server
308  /home/travis/gopath/src/github.com/IBM/cloudant-go-sdk/auth/couchdb_session_authenticator_test.go:108
309    Test authentication refresh [It]
310    /home/travis/gopath/src/github.com/IBM/cloudant-go-sdk/auth/couchdb_session_authenticator_test.go:215
311
312    Expected
313        <*http.Cookie | 0xc0000a9340>: {
314            Name: "AuthSession",
315            Value: "fakefake-2",
316            Path: "",
317            Domain: "",
318            Expires: 2021-02-10T14:23:33Z,
319            RawExpires: "Wed, 10 Feb 2021 14:23:33 GMT",
320            MaxAge: 0,
321            Secure: false,
322            HttpOnly: false,
323            SameSite: 0,
324            Raw: "AuthSession=fakefake-2; Expires=Wed, 10 Feb 2021 14:23:33 GMT",
325            Unparsed: nil,
326        }
327    to equal
328        <*http.Cookie | 0xc000428a50>: {
329            Name: "AuthSession",
330            Value: "fakefake-1",
331            Path: "",
332            Domain: "",
333            Expires: 2021-02-10T14:24:33Z,
334            RawExpires: "Wed, 10 Feb 2021 14:24:33 GMT",
335            MaxAge: 0,
336            Secure: false,
337            HttpOnly: false,
338            SameSite: 0,
339            Raw: "AuthSession=fakefake-1; Expires=Wed, 10 Feb 2021 14:24:33 GMT",
340            Unparsed: nil,
341        }
342
343    /home/travis/gopath/src/github.com/IBM/cloudant-go-sdk/auth/couchdb_session_authenticator_test.go:24
  ```
</p>
</details>

**To Reproduce**
Locally I could not reproduce, only during CI execution.

**Expected behavior**
The CI execution should be stable and not should fail because of a testing error.

**Additional context**
I think this is just a test implementation problem, the feature itself works well.

**Comment by eiri** [comment] 2021-02-10 13:21
Thanks for the report.

So how I read this is that on a starved for resources runner goroutines can be slow enough to start that [first of 3 parallel refreshers](https://github.com/IBM/cloudant-go-sdk/blob/master/auth/couchdb_session_authenticator_test.go#L240) will finish and update cookie, before last one start.

This is a test problem, but it's kind of hard to solve, because we are playing with timing of parallel runs here, inherently none-deterministic. I guess if this problem persist we'll just have to remove all parallel testing, it played its role in exposing races already.

**Comment by ricellis** [comment] 2021-02-15 09:29
I don't think this is restricted to a starved for resource runner, I reproduced it locally with lots of resource available.

**Comment by vmatyusGitHub** [comment] 2021-02-22 09:22
There is also possible to set some delay on the mocked server, this way we can ensure the authentication takes a certain time.
```go
time.Sleep(1 * time.Second)
```
It would be good to somehow stabilise the time factor in this test case.

**Comment by eiri** [comment] 2021-02-23 13:47
Problem with the adding delay into fake server is that it's essentially not a solution, but a band aid and just moving the problem down the line. We'll have to guess what will be the new delay for refreshers to finish and we still have a chance that if one of the client's goroutines is _really_ slow to start, like half-second slow, the last one of the clients still have the chance to unexpectedly get refreshed session. Not to mention, that this will make _every_ test to run at least a second+ and I'd prefer not to slow down the test suite unnecessary.

I'll self-assign this issue to see how it can be solved reliably and we can discuss it tomorrow.

**Comment by ricellis** [comment] 2021-02-23 14:57
IIUC the cookie assertion parts of this are also covered in other tests, but what we're really trying to test here is that `_session` is called only once even when there are competing threads for the refresh.
I think we should just stop asserting the old cookie value in each of the 3 threads, because it's entirely possible that the refresh has completed before they are scheduled.
Instead at the end of the test we could assert that the `_session` mock was called only once, as well as retaining the existing assertion that getCookie returns the new value.
If we want to continue to assert on the old cookie values, then I think asserting that _at least 1_ of the three threads received the old cookie would be sufficient.
that the value 
As such can't we just change this so that it asserts that the mock `_session` was called only once and that at least

**Comment by eiri** [comment] 2021-02-23 16:20
@ricellis yes, this is what I essentially end up doing in https://github.com/IBM/cloudant-go-sdk/pull/107

we need to keep that old cookie assertion to make sure our refresh process async and `auth` still serving old valid cookie even when refresh triggered

**Closed** 2021-02-24 15:32 UTC
